### ISSUE TITLE
Off by one in travel_back

### ISSUE THREAD

**Issue by tommack** [sparkfun/SparkFun_LumiDrive_Example_Code#1]
Doesn't this range need to start with `num_pixels - 1` and end with `-1`?  Or maybe just `reversed(range(0, num_pixels)`?

**Comment by edspark** [comment]
Hello, that's a great question! The range( ) function exhibits an include-exclude behavior. So, for example when we call the function "range" with 60 pixels as its parameter it _includes_ the number zero but _excludes_ the final number: sixty. This is convenient because as you may know, when we are addressing LEDs in our code, the first LED is actually the "zero-th" LED, if you catch my drift. We actually start counting at zero and not one, and the last LED is the number of pixels-1. 

Now if we look at the line of code that uses this function in the example code:

`for i in range(60):`

The iterator or variable, "i" will begin at 0 and finish at 59. Perfect! I hope this was helpful, let me know if there's anything else you have questions about!

**Comment by tommack** [comment]
It is the reverse loop that is problematic.

**Comment by edspark** [comment]
I realize that you were talking about `travel_back` not `travel`. You are absolutely right! I would and should have done `reversed(range(60))` as you mentioned.

**Comment by edspark** [comment]
Looks like were looking at this at the same time. I'll close out as soon as I fix it.

**Comment by edspark** [comment]
Fixed here: https://github.com/sparkfun/SparkFun_LumiDrive_Example_Code/commit/6d111d75e2b671ddd8ef19870f17dc023d62e7bf

Thanks for filing an issue @tommack!
